package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

const commit = "ea37f283d06e556dcffad036623107dc20f419c5"

var files = map[string]string{
	"Accessible.xml":            "42f14cab4d7dca97646c556c45c86614cb9948a7e6ff5cc9bd789e0198ec630a",
	"Action.xml":                "ae8df12ef63c6c50284e172ecc904f74b6431e4d4b961cf6da9c9207480fb588",
	"Application.xml":           "e5ac0e3c197b9a657e8347c8d0b5e7cd73ae4ce5b0a409b3a875a3aa7476ec08",
	"Cache.xml":                 "d89e329a4b9dd33fc6181371c853dce73250891dc15388b5666cd27cf433f350",
	"Collection.xml":            "9da9f6e16df1342410c2fddc60019e7fa9ab40aae45f719d32e20a5747d5a1d0",
	"Component.xml":             "ae87d87a4db76f0ab2f0aa8357a0392f71f1fa58b719990165cecb2bfa45d138",
	"DeviceEventController.xml": "bba4a41fb9c7ff9222a259c50041132af0ca1c0974373d6aeec269fee94a42c4",
	"DeviceEventListener.xml":   "bc4a6131b67336b1d50662431265d2355307a3e3bb299fb3d273149a6c6961e3",
	"Document.xml":              "945281061c6070e87b3cfa738abe505dcf35d59af73a09bb1ec09ac9643bde25",
	"EditableText.xml":          "2ea1b94822f19b0b00c80b918b89833cfb67d1eeef99d69b8421d0e6f40920ff",
	"Event.xml":                 "d4661d2bbcf5c6d03ba7a5d6d81c481eae803421796e69acebe1a277bbb19948",
	"Hyperlink.xml":             "45c70f2e691b9ee389dc0191e5b9749c37c29e2632acdcd0845772b62da613ec",
	"Hypertext.xml":             "60abc6df8bc4bf3d38bbade75f5494605d69f11bb24184ffcc0f51e43e6047d9",
	"Image.xml":                 "576ef8225934c380eee854fdc5754c6d714dcdaee84be6faca5addddaa2f43c1",
	"Registry.xml":              "1f175e58c08c8e02affceb06afc04284bcabebd1799d95c8c751525a286d9c2a",
	"Selection.xml":             "63eb9c10977192bb7cfb3e17684680101132b26c0b6277b2246e21eba27b1f8b",
	"Socket.xml":                "2a0393da237e31bb79057075ffa48b93d6f7299af518696bc211d122ec2c012d",
	"Table.xml":                 "833e2d1a7a394c5caa0684b881b9ce33e6dfd5414f54fb00e5f5aa4e1e190090",
	"TableCell.xml":             "c546d2477b867fad5bc3195a4d01cebe9cb9a70b298de171a0fb1c4aea1bb90a",
	"Text.xml":                  "602cdb27666912ac0cdf9ac53e5d718e002cd4fe1a37e9a9dc67c71f2acc4249",
	"Value.xml":                 "3fd8623364f0d8ac8bd2b7f5b23a055f74c35e8af0bb29076c8be10466f7a737",
}

type node struct {
	Interfaces []iface `xml:"interface"`
}
type iface struct {
	Name       string     `xml:"name,attr"`
	Methods    []member   `xml:"method"`
	Signals    []member   `xml:"signal"`
	Properties []property `xml:"property"`
}
type member struct {
	Name string `xml:"name,attr"`
}
type property struct {
	Name string `xml:"name,attr"`
	Type string `xml:"type,attr"`
}

func main() {
	output := flag.String("output", "zz_generated_interfaces.go", "output file")
	flag.Parse()
	client := &http.Client{Timeout: 30 * time.Second}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	interfaces := make([]iface, 0, len(names))
	for _, name := range names {
		url := fmt.Sprintf("https://raw.githubusercontent.com/GNOME/at-spi2-core/%s/xml/%s", commit, name)
		response, err := client.Get(url)
		if err != nil {
			fatalf("download %s: %v", name, err)
		}
		data, readErr := io.ReadAll(io.LimitReader(response.Body, 2<<20))
		_ = response.Body.Close()
		if readErr != nil || response.StatusCode != http.StatusOK {
			fatalf("download %s: status=%d err=%v", name, response.StatusCode, readErr)
		}
		digest := sha256.Sum256(data)
		if hex.EncodeToString(digest[:]) != files[name] {
			fatalf("digest mismatch for %s", name)
		}
		var parsed node
		if err := xml.Unmarshal(data, &parsed); err != nil {
			fatalf("parse %s: %v", name, err)
		}
		interfaces = append(interfaces, parsed.Interfaces...)
	}
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by tools/atspi-bindgen; DO NOT EDIT.")
	fmt.Fprintf(&source, "// Source: at-spi2-core %s (2.60.1).\n\n", commit)
	fmt.Fprintln(&source, "package atspi")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "const ATSPIXMLCommit = \""+commit+"\"")
	fmt.Fprintln(&source, "var InterfaceMetadata = map[string]InterfaceDescription{")
	for _, item := range interfaces {
		fmt.Fprintf(&source, "%q: {Name: %q, Methods: []string{%s}, Signals: []string{%s}, Properties: map[string]string{%s}},\n",
			item.Name, item.Name, quotedMembers(item.Methods), quotedMembers(item.Signals), quotedProperties(item.Properties))
	}
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatalf("format generated source: %v\n%s", err, source.Bytes())
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func quotedMembers(values []member) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%q", value.Name))
	}
	return strings.Join(parts, ",")
}
func quotedProperties(values []property) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%q:%q", value.Name, value.Type))
	}
	return strings.Join(parts, ",")
}
func fatalf(format string, values ...any) { fmt.Fprintf(os.Stderr, format+"\n", values...); os.Exit(1) }
